### DISCUSSION TITLE
approach to binding a directory (from host machine) to containers $HOME directory

### DISCUSSION THREAD

**Discussion by capsulecorplab** [accetto/ubuntu-vnc-xfce-g3#39] [Ideas]
Opening up this discussion thread for users who have or may want to build and/or run images configured via `docker-compose` and share use cases with example `docker-compose.yml` files

**Updated** by @accetto:
I've renamed this thread from `Building/running images from docker-compose` to `approach to binding a directory (from host machine) to containers $HOME directory` because the actual discussion has turned in that direction. I'll open a new thread named `Building/running images from docker-compose`.

**Comment by capsulecorplab** [comment]
Here's one such use case I'd like to explore https://github.com/accetto/ubuntu-vnc-xfce-g3/issues/40

**Reply by accetto** [reply]
Hello @capsulecorplab,

maybe you could rename this thread because the discusion has shifted towards `binding the whole $HOME directory`.

Then you can open the original subject `Building/running images from docker-compose` as a new thread.

What do you think?

Regards,
accetto

**Reply by accetto** [reply]
I've renamed the thread (see above).

**Comment by accetto** [comment]
Please note that this is a continuation of my answer to the question from the issue #40.

I'll split it into several posts, so we can comment each part separately.

The procedure described here works starting from the release `23.03.2`

****

If you don't need to extend the image and you really want to bind the whole `$HOME` directory, then my recommended `yaml` file would be something like this:

```yaml
version: "3"

volumes:
  my-home-volume

services:
  ubuntu-vnc-xfce-g3:
    image: accetto/ubuntu-vnc-xfce-g3:latest
    ports:
      - "25901:5901
      - "26901:6901
    environment:
      VNC_PW: "password"
    volumes:
      - type: volume
        source: my-home-volume
        target: /home/headles
```

**Comment by accetto** [comment]
If you'll bind the whole `$HOME` directory, then you'll probably get the problems that are described in the issues #36 and #37. I've tested it on Windows and Linux, with and without the Docker Desktop and it was always caused by biding the whole `$HOME `directory.

You can mitigate the black screen problem after the container restart by installing the package `libgl1`, but your profile will never be correctly initaliazed, if you bind the complete `$HOME` directory to an external folder on the host.

This is a big difference comparing to the managed environments, as for example Kasm Workspaces.

However, the profile will be initialized correctly, if you'll use Docker volumes, as I do in my recommended `yaml` above.

If you're willing to do some manual work, then you can use the following little trick for initializing your profile in bound directories. However, I haven't had enough time to test it by longer use.

It would would be really nice if some of you could help with that. We need to test, how newly created files will be handled. There are pretty big differences in handling the permissions in bound directories on different enwironments.

If the pattern will work correctly, then I could automate it later. So see the next post.

**Comment by accetto** [comment]
Let's use the following `helper.yml` file:

```yaml
version: "3"

volumes:
  my-home-volume:

services:

  init:
    profiles:
      - init-home
    image: accetto/ubuntu-vnc-xfce-g3:latest
    ports:
      - "25901:5901"
      - "26901:6901"
    environment:
      VNC_PW: "password"
    volumes:
      - type: volume
        source: my-home-volume
        target: /home/headless
      - type: bind
        source: ~/shared/my-home
        target: /home/headless-copy

  final:
    profiles:
      - shared-home
    image: accetto/ubuntu-vnc-xfce-g3:latest
    ports:
      - "25901:5901"
      - "26901:6901"
    environment:
      VNC_PW: "password"
    volumes:
      - type: bind
        source: ~/shared/my-home/headless
        target: /home/headless
```

The `yaml` file contains the configuration of two containers that are used in a sequence, as it's described in the next post.

**Warning!** Be sure to use the same password for both containers, otherwise the final container will enter the `view-only` mode.

Be also aware, that on Linux you have to create the folder `~/shared/my-home` manually before you create the first container. On Windows, on the other hand, it'll be created automatically. Note also that we assume a fresh new folder in both cases.
