### ISSUE TITLE
[way around] no screen/black screen after login - no logs (docker image on qnap NAS - container station)

### ISSUE THREAD

**Issue by accetto** [accetto/ubuntu-vnc-xfce-g3#56]
### Discussed in https://github.com/accetto/ubuntu-vnc-xfce-g3/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **thesearge** November 15, 2023</sup>
I pulled your docker image (firefox g3) from docker hub and created a container on my qnap. Container creation was made by ssh and docker commands as described in user guide. noVNC or VNC connection is no problem (tested port 36901 on container or 6901 directly). However after login with provided credentials „headless“ I only receive a dark screen. I tested different machines and browsers. I also recognized that there are no logs for this container in container-station (docker app for qnap). 
![IMG_0331](https://github.com/accetto/ubuntu-vnc-xfce-g3/assets/148621007/8f925f58-992e-496d-9f06-6561a4fa9767)
![IMG_0332](https://github.com/accetto/ubuntu-vnc-xfce-g3/assets/148621007/35ba071d-3094-4dff-a321-a33e55fb7865)
Need some help.</div>

**Comment by accetto** [comment]
Unfortunately I have to confirm this problem with the G3 containers and the Container Station on QNAP NAS devices.

I don't want to speculate about the reason until I do more testing.

As a way around you can use my older G2 or G1 images. They do work also on QNAP NAS devices.

This is the simple Container Station application I've used for testing:

```yaml
### app name: app-qnap-test
version: "3"
services:
  firefox-g3:
    image: accetto/ubuntu-vnc-xfce-firefox-g3:latest
    ports:
      - "35940:5901"
      - "35941:6901"
  firefox-g2:
    image: accetto/xubuntu-vnc-novnc-firefox:latest
    ports:
      - "35942:5901"
      - "35943:6901"
  firefox-g1:
    image: accetto/ubuntu-vnc-xfce-firefox-plus:latest
    ports:
      - "35944:5901"
      - "35945:6901"
```

You can connect to the containers using your web browser like this:

```shell
http://<your-nas-ip>:35941
http://<your-nas-ip>:35943
http://<your-nas-ip>:35945
```

The first container will show only a black-screen, but the other two should work.

**Comment by accetto** [comment]
FYI
Increasing shared memory like this didn't help.

```yaml
version: "3"
services:
  firefox-g3:
    image: accetto/ubuntu-vnc-xfce-firefox-g3:latest
    ports:
      - "35940:5901"
      - "35941:6901"
    shm_size: "256m"
```

**Comment by accetto** [comment]
FYI
Making the container privileged did help, so it seems to be related to the permissions on QNAP.

The following G3 container should work:

```yaml
version: "3"
services:
  firefox-g3:
    image: accetto/ubuntu-vnc-xfce-firefox-g3:latest
    ports:
      - "35940:5901"
      - "35941:6901"
    shm_size: "256m"
    privileged: true
```

**Comment by accetto** [comment]
FYI: Test 3
Pre-creating the network manually didn't help.

The following G3 container will not work:

```yaml
version: "3"
networks:
  my_test:
    external: true
    name: my_test
services:
  firefox-g3:
    image: accetto/ubuntu-vnc-xfce-firefox-g3:latest
    ports:
      - "35940:5901"
      - "35941:6901"
    networks:
      - my_test
```
